apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  # kube-prometheus-stack은 helm으로 설치 필요 (README.md 참고)
  # helm upgrade --install monitor prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace -f values-monitor.yaml
  - grafana-ingress.yaml
  - prometheus-ingress.yaml

