apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
spec:
  ingressClassName: nginx
  # TLS 인증서가 없는 경우 tls 섹션 주석 처리
  # tls:
  #   - hosts:
  #       - prometheus.vitamin7.org
  #     secretName: prometheus-tls
  rules:
    - host: prometheus.vitamin7.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor-kube-prometheus-st-prometheus
                port:
                  number: 9090
