apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vibot
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
