apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-tools
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - jnlp-service.yaml
  - ingress.yaml

