apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql-backup
resources:
  - namespace.yaml
  - configmap.yaml
  - recovery-configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

